-- MySQL Script generated by MySQL Workbench
-- mar 31 mar 2015 22:04:06 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web_dojo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_dojo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_dojo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `web_dojo` ;

-- -----------------------------------------------------
-- Table `web_dojo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dojo`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(255) NULL,
  `pass` VARCHAR(255) NULL,
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC),
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB
COMMENT = 'Tabla de usuarios del sistema';


-- -----------------------------------------------------
-- Table `web_dojo`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dojo`.`files` (
  `idfiles` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `owner` INT NOT NULL,
  `joinHash` VARCHAR(45) NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `last_access_time` DATETIME NOT NULL,
  `trash` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idfiles`),
  INDEX `fk_files_1_idx` (`owner` ASC),
  CONSTRAINT `fk_files_1`
    FOREIGN KEY (`owner`)
    REFERENCES `web_dojo`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'En ellla se representan los archivos\n';


-- -----------------------------------------------------
-- Table `web_dojo`.`edition_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dojo`.`edition_state` (
  `idstate` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_dojo`.`editors_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dojo`.`editors_state` (
  `ideditors_state` INT NOT NULL AUTO_INCREMENT,
  `idfiles` INT NOT NULL,
  `idusers` INT NOT NULL,
  `idstate` INT NOT NULL,
  PRIMARY KEY (`ideditors_state`),
  INDEX `fk_editors_state_1_idx` (`idfiles` ASC),
  INDEX `fk_editors_state_2_idx` (`idstate` ASC),
  INDEX `UNIQUE file user` (`idfiles` ASC, `idusers` ASC),
  CONSTRAINT `fk_editors_state_1`
    FOREIGN KEY (`idfiles`)
    REFERENCES `web_dojo`.`files` (`idfiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editors_state_2`
    FOREIGN KEY (`idstate`)
    REFERENCES `web_dojo`.`edition_state` (`idstate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editors_state_3`
    FOREIGN KEY (`idusers`)
    REFERENCES `web_dojo`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
